# Generated by Django 3.1.7 on 2021-03-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='datalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('last_occurrence', models.DateTimeField(auto_now_add=True)),
                ('device_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.source')),
            ],
        ),
    ]
