# Generated by Django 3.1.7 on 2021-03-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='is_active',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
