# Generated by Django 3.1.7 on 2021-03-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_datalog_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalog',
            name='device_ID',
        ),
        migrations.DeleteModel(
            name='source',
        ),
    ]
