# Generated by Django 3.1.7 on 2021-03-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210328_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='last_occurrence',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
