# Generated by Django 3.1.7 on 2021-03-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210328_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='is_active',
            field=models.CharField(max_length=50),
        ),
    ]
